CREATE OR REPLACE PROCEDURE PROCESSMONTHLYINTEREST

IS 

V_ACCOUNTID ACCOUNTS.ACCOUNTID%TYPE;
V_BALANCE ACCOUNTS.BALANCE%TYPE;

CURSOR ACCOUNTS_CUR IS 
    SELECT ACCOUNTID, BALANCE 
    FROM ACCOUNTS
    WHERE ACCOUNTTYPE = 'Savings'
    FOR UPDATE; -- LOCK 


BEGIN

    OPEN ACCOUNTS_CUR;

    LOOP
        FETCH ACCOUNTS_CUR INTO V_ACCOUNTID, V_BALANCE;

        EXIT WHEN ACCOUNTS_CUR%NOTFOUND;

        V_BALANCE := V_BALANCE * 1.01;


        UPDATE ACCOUNTS
        SET BALANCE = V_BALANCE, LASTMODIFIED = SYSDATE
        WHERE ACCOUNTID = V_ACCOUNTID;

    END LOOP;

        COMMIT;

    CLOSE ACCOUNTS_CUR;

    DBMS_OUTPUT.PUT_LINE('Monthly interest processed successfully for all savings accounts.');

EXCEPTION
    WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE('Error during monthly interest processing: ' || SQLERRM);
         
         ROLLBACK;

END PROCESSMONTHLYINTEREST;
/