-- ALTER TABLE CUSTOMERS 
-- ADD ISVIP VARCHAR2(6);


DECLARE 
    CURSOR CUSTOMER_CUR IS
    SELECT CUSTOMERID ,BALANCE FROM CUSTOMERS;

V_CUSTOMERID CUSTOMERS.CUSTOMERID%TYPE;
V_BALANCE CUSTOMERS.BALANCE%TYPE;

BEGIN
    OPEN CUSTOMER_CUR;
    LOOP 
        FETCH CUSTOMER_CUR INTO V_CUSTOMERID, V_BALANCE;
        EXIT WHEN CUSTOMER_CUR%NOTFOUND;

        IF V_BALANCE > 1000 THEN
        UPDATE CUSTOMERS 
        SET ISVIP = 'TRUE'
        WHERE CUSTOMERID = V_CUSTOMERID;

        ELSE
            UPDATE CUSTOMERS 
            SET ISVIP = 'FALSE'
            WHERE CUSTOMERID = V_CUSTOMERID;

        END IF;

    END LOOP;

    COMMIT;
    CLOSE CUSTOMER_CUR;

        DBMS_OUTPUT.PUT_LINE('vip status to eligible customers.');
END;
/