DECLARE 
    CURSOR CUSTOMER_CUR IS
    SELECT C.NAME, L.ENDDATE
    FROM CUSTOMERS C, LOANS L
    WHERE C.CUSTOMERID = L.CUSTOMERID AND 
    L.ENDDATE BETWEEN SYSDATE AND SYSDATE + 30;

V_NAME CUSTOMERS.NAME%TYPE;
V_ENDATE LOANS.ENDDATE%TYPE;

BEGIN
    OPEN CUSTOMER_CUR;
    LOOP 
        FETCH CUSTOMER_CUR INTO V_NAME, V_ENDATE;
        EXIT WHEN CUSTOMER_CUR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('Remainder has been Sent to '|| V_NAME || ' and End date is : ' || V_ENDATE);

    END LOOP;

    COMMIT;
    CLOSE CUSTOMER_CUR;

        DBMS_OUTPUT.PUT_LINE('DONE');
END;
/